<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>5d663a86-e665-48e0-a2c9-89711c589f3d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="src\RiskReward.Core\RiskReward.Core.csproj" />
    <ProjectReference Include="src\RiskReward.Infrastructure\RiskReward.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="src\**\*.cs;tests\**\*.cs" />
    <Content Remove="src\**;tests\**" />
    <None Remove="src\**;tests\**" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></None>
  </ItemGroup>
</Project>
